services:
  db:
    image: postgis/postgis
    restart: always
    environment:
      - POSTGRES_DB=searchsmartly
      - POSTGRES_USER=searchsmartly
      - POSTGRES_PASSWORD=searchsmartly
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - network

  web:
    build: .
    command: python searchsmartly/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - network

volumes:
  postgres_data:

networks:
  network: